export type ImposterWord = {
  word: string
  hint: string
}

// Default corpus. Each hint is loosely related to the word so the imposter
// can bluff without being handed the answer.
export const DEFAULT_IMPOSTER_WORDS: ImposterWord[] = [
  // Food & drink
  { word: 'Pizza', hint: 'Italy' },
  { word: 'Sushi', hint: 'Rice' },
  { word: 'Taco', hint: 'Shell' },
  { word: 'Burger', hint: 'Grill' },
  { word: 'Pancake', hint: 'Breakfast' },
  { word: 'Popcorn', hint: 'Movie' },
  { word: 'Chocolate', hint: 'Sweet' },
  { word: 'Coffee', hint: 'Morning' },
  { word: 'Ice Cream', hint: 'Cold' },
  { word: 'Momo', hint: 'Dumpling' },
  { word: 'Spaghetti', hint: 'Noodle' },
  { word: 'Croissant', hint: 'Bakery' },
  { word: 'Watermelon', hint: 'Summer' },
  { word: 'Banana', hint: 'Yellow' },
  { word: 'Avocado', hint: 'Green' },
  { word: 'Honey', hint: 'Sticky' },
  { word: 'Popsicle', hint: 'Stick' },
  { word: 'Cheese', hint: 'Dairy' },
  { word: 'Curry', hint: 'Spice' },
  { word: 'Boba Tea', hint: 'Straw' },
  { word: 'Donut', hint: 'Hole' },
  { word: 'Lemonade', hint: 'Sour' },
  { word: 'Wine', hint: 'Grape' },
  { word: 'Cereal', hint: 'Bowl' },
  // Places
  { word: 'Beach', hint: 'Sand' },
  { word: 'Airport', hint: 'Travel' },
  { word: 'Hospital', hint: 'Doctor' },
  { word: 'Library', hint: 'Quiet' },
  { word: 'Casino', hint: 'Luck' },
  { word: 'Gym', hint: 'Sweat' },
  { word: 'Zoo', hint: 'Animals' },
  { word: 'Museum', hint: 'History' },
  { word: 'Prison', hint: 'Bars' },
  { word: 'Volcano', hint: 'Hot' },
  { word: 'Desert', hint: 'Dry' },
  { word: 'Jungle', hint: 'Trees' },
  { word: 'Mount Everest', hint: 'Climb' },
  { word: 'Paris', hint: 'Tower' },
  { word: 'Las Vegas', hint: 'Lights' },
  { word: 'Space Station', hint: 'Orbit' },
  { word: 'Submarine', hint: 'Underwater' },
  { word: 'Haunted House', hint: 'Scary' },
  { word: 'Wedding', hint: 'Ceremony' },
  { word: 'Classroom', hint: 'Desk' },
  { word: 'Supermarket', hint: 'Cart' },
  { word: 'Igloo', hint: 'Ice' },
  { word: 'Castle', hint: 'King' },
  { word: 'Farm', hint: 'Barn' },
  { word: 'Amusement Park', hint: 'Rides' },
  { word: 'Cinema', hint: 'Screen' },
  // Animals
  { word: 'Elephant', hint: 'Trunk' },
  { word: 'Giraffe', hint: 'Tall' },
  { word: 'Penguin', hint: 'Antarctica' },
  { word: 'Kangaroo', hint: 'Australia' },
  { word: 'Shark', hint: 'Fin' },
  { word: 'Octopus', hint: 'Ink' },
  { word: 'Owl', hint: 'Night' },
  { word: 'Snake', hint: 'Hiss' },
  { word: 'Panda', hint: 'Bamboo' },
  { word: 'Dolphin', hint: 'Smart' },
  { word: 'Lion', hint: 'Mane' },
  { word: 'Bee', hint: 'Buzz' },
  { word: 'Spider', hint: 'Web' },
  { word: 'Camel', hint: 'Hump' },
  { word: 'Peacock', hint: 'Feathers' },
  { word: 'Dinosaur', hint: 'Fossil' },
  { word: 'Unicorn', hint: 'Myth' },
  { word: 'Dragon', hint: 'Fire' },
  { word: 'Cat', hint: 'Pet' },
  { word: 'Frog', hint: 'Pond' },
  // Objects
  { word: 'Umbrella', hint: 'Rain' },
  { word: 'Toothbrush', hint: 'Bathroom' },
  { word: 'Guitar', hint: 'Strings' },
  { word: 'Piano', hint: 'Keys' },
  { word: 'Camera', hint: 'Photo' },
  { word: 'Mirror', hint: 'Reflection' },
  { word: 'Candle', hint: 'Wax' },
  { word: 'Backpack', hint: 'School' },
  { word: 'Headphones', hint: 'Music' },
  { word: 'Balloon', hint: 'Party' },
  { word: 'Scissors', hint: 'Cut' },
  { word: 'Telescope', hint: 'Stars' },
  { word: 'Ladder', hint: 'Climb' },
  { word: 'Pillow', hint: 'Bed' },
  { word: 'Wallet', hint: 'Money' },
  { word: 'Sunglasses', hint: 'Sun' },
  { word: 'Clock', hint: 'Time' },
  { word: 'Key', hint: 'Lock' },
  { word: 'Map', hint: 'Directions' },
  { word: 'Crown', hint: 'Royal' },
  { word: 'Sword', hint: 'Knight' },
  { word: 'Microwave', hint: 'Kitchen' },
  { word: 'Remote Control', hint: 'TV' },
  { word: 'Skateboard', hint: 'Wheels' },
  { word: 'Bicycle', hint: 'Pedal' },
  { word: 'Helicopter', hint: 'Blades' },
  { word: 'Rocket', hint: 'Launch' },
  { word: 'Treasure Chest', hint: 'Pirate' },
  { word: 'Snowman', hint: 'Winter' },
  { word: 'Fireworks', hint: 'Celebration' },
  // Activities & jobs
  { word: 'Swimming', hint: 'Water' },
  { word: 'Soccer', hint: 'Goal' },
  { word: 'Basketball', hint: 'Hoop' },
  { word: 'Chess', hint: 'Strategy' },
  { word: 'Yoga', hint: 'Stretch' },
  { word: 'Camping', hint: 'Tent' },
  { word: 'Karaoke', hint: 'Sing' },
  { word: 'Fishing', hint: 'Patience' },
  { word: 'Skiing', hint: 'Snow' },
  { word: 'Surfing', hint: 'Waves' },
  { word: 'Bowling', hint: 'Pins' },
  { word: 'Dancing', hint: 'Rhythm' },
  { word: 'Painting', hint: 'Brush' },
  { word: 'Cooking', hint: 'Recipe' },
  { word: 'Gardening', hint: 'Plants' },
  { word: 'Firefighter', hint: 'Rescue' },
  { word: 'Astronaut', hint: 'Space' },
  { word: 'Chef', hint: 'Hat' },
  { word: 'Detective', hint: 'Clues' },
  { word: 'Pilot', hint: 'Cockpit' },
  { word: 'Magician', hint: 'Trick' },
  { word: 'Dentist', hint: 'Teeth' },
  { word: 'Teacher', hint: 'Lesson' },
  { word: 'Pirate', hint: 'Ship' },
  { word: 'Ninja', hint: 'Stealth' },
  { word: 'Vampire', hint: 'Blood' },
  { word: 'Zombie', hint: 'Undead' },
  { word: 'Superhero', hint: 'Cape' },
  { word: 'Robot', hint: 'Machine' },
  { word: 'Ghost', hint: 'Spooky' },
  // Things & concepts
  { word: 'Rainbow', hint: 'Colors' },
  { word: 'Thunderstorm', hint: 'Loud' },
  { word: 'Moon', hint: 'Night' },
  { word: 'Sun', hint: 'Bright' },
  { word: 'Tornado', hint: 'Spin' },
  { word: 'Earthquake', hint: 'Shake' },
  { word: 'Birthday', hint: 'Cake' },
  { word: 'Halloween', hint: 'Costume' },
  { word: 'Christmas', hint: 'Gifts' },
  { word: 'Valentine', hint: 'Love' },
  { word: 'Dream', hint: 'Sleep' },
  { word: 'Internet', hint: 'Online' },
  { word: 'Selfie', hint: 'Phone' },
  { word: 'Netflix', hint: 'Binge' },
  { word: 'TikTok', hint: 'Scroll' },
  { word: 'Video Game', hint: 'Controller' },
  { word: 'Olympics', hint: 'Medal' },
  { word: 'Harry Potter', hint: 'Wizard' },
  { word: 'Star Wars', hint: 'Galaxy' },
  { word: 'Titanic', hint: 'Iceberg' },
]
